### ISSUE TITLE
Connected client crashes after another client disconnects

### ISSUE THREAD

**Issue by stes** [stes/Space-Warrior#47]
Exception stack trace:

Exception in thread "Thread-3" java.lang.NullPointerException
    at sw.client.GameController.snapshot(GameController.java:172)
    at sw.client.SWClient.receivedMessage(SWClient.java:113)
    at sw.shared.net.UDPHost.invokeReceivedMessage(UDPHost.java:209)
    at sw.shared.net.UDPConnection.received(UDPConnection.java:162)
    at sw.shared.net.UDPHost.messageReceived(UDPHost.java:258)
    at sw.shared.net.UDPHost.run(UDPHost.java:152)
Exception in thread "main" java.lang.NullPointerException
    at sw.client.gui.GamePanel$PlayerTableModel.getValueAt(GamePanel.java:352)
    at javax.swing.JTable.getValueAt(Unknown Source)
    at javax.swing.JTable.prepareRenderer(Unknown Source)
    at javax.swing.plaf.basic.BasicTableUI.paintCell(Unknown Source)
    at javax.swing.plaf.basic.BasicTableUI.paintCells(Unknown Source)
    at javax.swing.plaf.basic.BasicTableUI.paint(Unknown Source)
    at javax.swing.plaf.ComponentUI.update(Unknown Source)
    at javax.swing.JComponent.paintComponent(Unknown Source)
    at javax.swing.JComponent.paint(Unknown Source)
    at javax.swing.JComponent.paintChildren(Unknown Source)
    at javax.swing.JComponent.paint(Unknown Source)
    at javax.swing.JViewport.paint(Unknown Source)
    at javax.swing.JComponent.paintChildren(Unknown Source)
    at javax.swing.JComponent.paint(Unknown Source)
    at java.awt.Component.lightweightPaint(Unknown Source)
    at java.awt.Container.lightweightPaint(Unknown Source)
    at java.awt.GraphicsCallback$PeerPaintCallback.run(Unknown Source)
    at sun.awt.SunGraphicsCallback.runOneComponent(Unknown Source)
    at java.awt.Component.paintAll(Unknown Source)
    at java.awt.GraphicsCallback$PaintAllCallback.run(Unknown Source)
    at sun.awt.SunGraphicsCallback.runOneComponent(Unknown Source)
    at sun.awt.SunGraphicsCallback.runComponents(Unknown Source)
    at java.awt.Container.paintComponents(Unknown Source)
    at sw.client.gui.GamePanel.render(GamePanel.java:119)
    at sw.client.SWFrame.render(SWFrame.java:307)
    at sw.client.SWFrame.gameLoop(SWFrame.java:182)
    at sw.client.SWFrame.<init>(SWFrame.java:129)
    at sw.client.Program.main(Program.java:30)

occurred in 79924d9aeb179b4d8b1a445cdba10e6d2e8359f6

**Comment by axblk** [comment]
seems to be fixed
