### ISSUE TITLE
fix class cast exception (causes client to crash)

### ISSUE THREAD

**Issue by stes** [stes/Space-Warrior#59]
stack trace:

Exception in thread "main" java.lang.ClassCastException: sw.shared.data.entities.shots.LaserBeam cannot be cast to sw.shared.data.entities.IImageEntity
    at sw.client.gui.sprites.ImageSprite.render(ImageSprite.java:46)
    at sw.client.gui.sprites.ParticleSprite.render(ParticleSprite.java:48)
    at sw.client.gui.PlayingFieldPanel.render(PlayingFieldPanel.java:125)
    at sw.client.gui.GamePanel.render(GamePanel.java:181)
    at sw.client.SWFrame.render(SWFrame.java:175)
    at sw.client.SWFrame.renderLoop(SWFrame.java:222)
    at sw.client.SWFrame.<init>(SWFrame.java:128)
    at sw.client.Program.main(Program.java:30)

**Comment by stes** [comment]
should be fixed by 1d05b8ad9bc6378e4c3b7d83fca799af403ab105
