### ISSUE TITLE
fix problem in particle system

### ISSUE THREAD

**Issue by stes** [stes/Space-Warrior#63]
Exception in thread "Thread-20" java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 13
    at java.util.Vector.remove(Unknown Source)
    at sw.client.psystem.ParticleSystem.tick(ParticleSystem.java:225)
    at sw.client.psystem.ParticleSystem.access$4(ParticleSystem.java:217)
    at sw.client.psystem.ParticleSystem$1.run(ParticleSystem.java:195)

**Comment by stes** [comment]
fixed by d76d61f55a4a6d0541da331973a3dbfb4852bbdc
